### ISSUE TITLE
Incorrect menu screen

### ISSUE THREAD

**Issue by MSLaFaver** [EmK530/BRMods#1]
This mod works really well, but it's doing weird things on the menu screen.
![Screenshot 2024-02-29 002515](https://github.com/EmK530/BRMods/assets/93147703/6ae7cb88-4eef-4a68-90a3-3e9ba1889d94)

**Comment by EmK530** [comment]
Something must be off with scaling, what mod version is this?
Also it could help knowing what window mode was used:
Windowed, Maximized or Fullscreen.

**Comment by EmK530** [comment]
Ah I think I see now, certain resolutions have issues in fullscreen.
Sorry, I only tested on 1920x1080. I shall look closer for a fix.

**Comment by EmK530** [comment]
@ScientificGuy See if [Version 1.3.0](https://github.com/EmK530/BRMods/raw/main/BRML/NativeResolution/Release/Legacy%20Versions/EmK530-NativeResolution-1.3.0.zip) solves your issue.

**Comment by MSLaFaver** [comment]
@EmK530 I'm afraid it didn't work. Same issue as last time. This was in fullscreen mode in both 1.2.0 and 1.3.0 on a 3456x2160 display. My laptop screen doesn't have a 16:9 aspect ratio.

EDIT: Haha I figured it out! Turns out removing lines 9 through 13 (in 1.3.0) actually works, preserving the dev's intended 16:9 ratio while still upscaling the game. I don't think the mod should even support other aspect ratios since it breaks the viewport, so this seems like the right fix.

**Comment by MSLaFaver** [comment]
Just another thing here, there's an irritating single-pixel line at the top of the screen now, I think this is just a result of the upscale. Not sure if anything can be done about this, but just wondering.
![image](https://github.com/EmK530/BRMods/assets/93147703/bcaf328d-9f12-4c06-885e-66fb0fb7d2f9)

**Comment by EmK530** [comment]
> This was in fullscreen mode in both 1.2.0 and 1.3.0 on a 3456x2160 display. My laptop screen doesn't have a 16:9 aspect ratio.
> Turns out removing lines 9 through 13 (in 1.3.0) actually works

Seems I have to do more resolution testing because I had only tested lower resolutions as a way of messing with aspect ratio
I'll try to recreate your resolution when I have time
Wouldn't want to remove code for switching scale mode as it probably breaks support for windowed and maximized

**Comment by MSLaFaver** [comment]
Actually, seeing the mod work perfectly in windowed mode was what gave me the idea to remove the code in the first place. If you give it a try with a non 16:9 screen you’ll see what I mean. I’ve been testing it for the last couple hours and it works great.

**Comment by EmK530** [comment]
For me fullscreen would break without the alternate scale mode, maybe not for your high resolution.
Gotta simulate it and find out what rules to add to the code

**Comment by EmK530** [comment]
No clue what's going on but for some reason I can use scale mode 1 without issue now, I'll have this be the new standard.
Maybe for 2.0 I can hopefully allow custom aspect.
