### ISSUE TITLE
Light line at top of screen

### ISSUE THREAD

**Issue by MSLaFaver** [EmK530/BRMods#2]
I don’t think this was addressed in the previous closed issue so I’ll bring it up here. In 1.2.0 and 1.3.0, there is a pixel-high light line at the top of the screen.
![image](https://github.com/EmK530/BRMods/assets/93147703/e70f3137-3d20-4e3e-873d-c2fd765f2d37)

**Comment by EmK530** [comment]
The line looks like a portion not affected by the UI color filter, because of how the UI is anchored I don't know if this is fixable until I figure out object modification

**Comment by EmK530** [comment]
Nevermind wasn't so bad to learn and also my assumption was right
Hopefully [Version 1.5.0](https://github.com/EmK530/BRMods/raw/main/BRML/NativeResolution/Release/Legacy%20Versions/EmK530-NativeResolution-1.5.0.zip) solves this for you, it did for me

**Comment by MSLaFaver** [comment]
Excellent, it works at my resolution!
