### ISSUE TITLE
Linux compatibility

### ISSUE THREAD

**Issue by RondoRevolution** [EmK530/BRMods#3]
Is there any plans to make the mod compatible with Linux?

The game runs natively but the mod doesn't seem to work right now. I've tried putting the files inside the root folder of the game and inside a mods folder in the game's directory.

**Comment by EmK530** [comment]
Do you have [BRML](https://github.com/AGO061/BuckshotRouletteModLoader)? (Buckshot Roulette Mod Loader)
Note that it is not updated for v1.2.0 yet.

**Comment by RondoRevolution** [comment]
Oh, I don't. Could you add instructions to the readme for this? I found this mod by searching for a ultrawide fix, I didn't know it needed BRML to work. I'll wait for BRML to be updated then, thanks.

**Comment by EmK530** [comment]
Either that or I can try to modify the batch version, it uses the --script flag to run the mod.

**Comment by EmK530** [comment]
I've edited the BRML script to be compatible with the --script flag and posted it [here](https://github.com/EmK530/BRMods/blob/main/Batch/NativeResolution/mod_main.gd)
